### PR TITLE
Updated Yandex icon

### PR DESCRIPTION
**Pull request by DotTheI**

### CODE REVIEW

**Comment by pilotmoon** [comment]
Thanks! Now updated at https://www.popclip.app/extensions/x/1bgbbm

**Comment by DotTheI** [comment]
@pilotmoon, thank you! Just noticed the icon turned out a little taller than those of the other extensions. How many pixels should be between the logo itself and the image border?

Also, is there a way to use the English logo depending on the PopClip language?

**Comment by pilotmoon** [comment]
You're right; it did look a little big! There's no "official design standard," but I usually leave a margin. The easiest way to adjust the size is to use an [icon transformation](https://www.popclip.app/dev/icons#geometric-transformations), like this:

`icon: scale=90 file:yandex.png`

I have already [made this adjustment](https://github.com/pilotmoon/PopClip-Extensions/commit/3aeb5af6cf8fd1ef2591ab608894dfd3ec6d3f10).

PopClip doesn't support showing different icons based on the user's language.

**Comment by DotTheI** [comment]
@pilotmoon, you may want to update the description of the extension, too, to change the URL from yandex.ru to ya.ru. The company has undergone some weird restructuring so that yandex.ru now redirects to dzen.ru, although yandex.ru/search/?text=example is working as it always has

**Pull request merged**
