### PR TITLE
Add API domain option

### PR DESCRIPTION
**Pull request by chentao1006**
Add option to specify API base domain and update API request URL. Allow user to change the default OpenAI API to customized domain.

### CODE REVIEW

**Comment by pilotmoon** [comment]
Thanks @chentao1006 , this looks good. I'm not familiar with the use of alternative domains for the OpenAI API. To help me understand the change, can you describe when alternate domains might typically be used? Fill me in on the typical use case.

**Comment by chentao1006** [comment]
Custom domains for the OpenAI API are used in various scenarios. One common use case is when users want to build their own OpenAI API infrastructure, including setting up reverse proxies or integrating different large models. By using custom domains, users can customize and manage the API requests based on their specific requirements.

Additionally, some users may need to integrate multiple OpenAI accounts or different models. With custom domains, they can assign different domains to each model or account, facilitating better management and differentiation.

**Comment by pilotmoon** [comment]
Awesome. All makes sense. Thanks!

**Comment by chentao1006** [comment]
Thank you!

**Comment by pilotmoon** [comment]
Update published to: https://www.popclip.app/extensions/x/48f32j

**Pull request merged**
