### PR TITLE
Update iterm2.applescript

### PR DESCRIPTION
**Pull request by nikolalek**
edit current terminal to current window

### CODE REVIEW

**Comment by invariant** [comment]
Could you explain the reason for the change? I tried it in Script Editor and the version with "window" fails to compile in Script Editor.

**Comment by nikolalek** [comment]
For iTerm2 2.1+ version works with the terminal and does not work with the version of the window, for iTerm2 2.9+ version works with the window and does not work with the terminal. Just I was standing and the main beta version I did not work :(
Why is it so unfortunately I do not know.

**Comment by invariant** [comment]
Ah I see, thank you.

**Comment by invariant** [comment]
I have used this to make a new version of the extension, with two different scripts and an option to select which to use.

**Pull request closed without merging**
