### PR TITLE
Added Neeva.com Search Extension

### PR DESCRIPTION
**Pull request by pouyakary**
This is a copy of DuckDuckGo package for the Neeva.com Search Engine.

### CODE REVIEW

**Comment by pilotmoon** [comment]
Hello, thanks for this. I see you have submitted a compiled extension to the extension directory. Please submit only source files to the source-contrib directory, as per the contributing guidelines in Readme.

**Comment by pouyakary** [comment]
@pilotmoon you're welcome and sure! I'll do!

**Comment by pouyakary** [comment]
So I fixed the neeva problem and I also added the [phind](https://phind.com) search extension

**Review by pilotmoon — APPROVED** [review]

**Comment by pilotmoon** [comment]
Thank you!

**Pull request merged**
