### PR TITLE
Update QR Generator

### PR DESCRIPTION
**Pull request by bimawa**
Wrote a simple `qrgen` command on Rust to make it more usefully. 
Also moved to `qlmanage`  for quick look of the result.

### CODE REVIEW

**Comment by invariant** [comment]
Hi I just tried it out. This is really great, it works very well. 

Would it be possible to have a copy of the Rust source source? I'm dubious about having a binary that can't be examined, or edited in future.

**Comment by invariant** [comment]
Merged in b527d4b

Will move this to contrib folder now along with all user-submitted extensions (doing a re-org).

**Comment by bimawa** [comment]
Missing your message, :( It was hard to find this code xD.
But I found it!
Maybe we should hold some folder for src in different languages?
And where is the best way to save it? Or can I attach a zip here?

**Comment by pilotmoon** [comment]
I think best to add the source code into the repo inside the extensions folder itself.

**Pull request closed without merging**
