### PR TITLE
Updated TextSoap extension to support TextSoap 8 instead of TextSoap 7

### PR DESCRIPTION
**Pull request by onecrayon**
Note that I didn't modify the .popclipextz file (since that requires code signing, I figured there wasn't much point).

This is not backwards compatible with TextSoap 7, unfortunately, so I added the version number to the extension description.

### CODE REVIEW

**Comment by invariant** [comment]
Thank you!

**Comment by WolfieUSA** [comment]
Wow, almost six years on and now we have the same issue with TextSoap 9! Any chance that this will be fixed?

**Comment by invariant** [comment]
* insert rant about paid updates pointlessly breaking compatibility and causing everybody needless work *

I've got it on my huge and growing todo list. The textsoap dev did tweet that he was going to update the PopClip extension, so I've been waiting,… honestly I am so snowed under I don't even know what task to start on next it might as well be this one, shrug emoji

**Comment by invariant** [comment]
Apologies for snarkiness.

**Pull request merged**
