### PR TITLE
Adding Readwise PopClip Extension

### PR DESCRIPTION
**Pull request by gcaprio**
This PR adds the ability for sending the highlighted text in a web browser to the Readwise service. 

I used the Pinboard extension as inspiration, so happy to make any changes necessary to conform to any coding standards.

### CODE REVIEW

**Comment by invariant** [comment]
Thanks for this! Finally got round to checking it out. It works great when I use it in a supported browser because the source URL and Browser Title fields are available to the script. But if I use it in Firefox (which does not support those fields) or in a non-browser, the extension fails with the "X" because it tries to send an invalid string as source URL to the API. Can it be modified to succeed when the source url is unavailable?

**Comment by gcaprio** [comment]
Yup, good catch. I'll make those updates and update the PR this week.

**Comment by gcaprio** [comment]
@invariant we should be all set. Source URL and Title are now optional. LMK what you think.

**Comment by invariant** [comment]
Pushed to site, cheers!
https://pilotmoon.com/popclip/extensions/page/Readwise

**Pull request closed without merging**
