### PR TITLE
Add Hypothesis extension

### PR DESCRIPTION
**Pull request by cdpath**
PopClip extension for [Hypothesis](https://web.hypothes.is/).

Highly influenced by readwise extension.

### CODE REVIEW

**Comment by cdpath** [comment]
> @cdpath I tried to install this extension but it doesnt seem to login after pasting hypothesis key

Can you try this 'compiled' version? https://github.com/cdpath/hypothesis_it/releases/tag/v0.0.2

**Comment by invariant** [comment]
Thanks for this. Nice job! 

The reason it was failing for @danieltomasz is that the extension needs the `network` entitlement, which was missing from the config file. I've added that in 0492a20.

Being not a Hypothesis user I haven't been able to test it properly yet. There are some improvements that I would make before I would publish this to the main directory, including using the OAuth properly to sign in. But, still looks useful as it is so have fun!

ps. I'll be moving all user-contributed extensions to a different source directory in the near future so be forewarned it may move.

**Comment by danieltomasz** [comment]
@invariant  After trying to install newly added `Hypothesis,popclipextz` I am getting following error
```
Cannot Install Extension
Failed to unzip extension.
Extension: Hypothesis.popclipextz
```

**Comment by invariant** [comment]
@danieltomasz Can you try again, I have rebuilt it since then.
https://github.com/pilotmoon/PopClip-Extensions/raw/master/extensions/Hypothesis.popclipextz

**Comment by danieltomasz** [comment]
it's ok now! thanks!

**Pull request merged**
